#!/bin/bash

STATUS=$(acpi | awk '{print $3}')

if [[ $STATUS == 'Discharging,' ]]; then
  LEVEL=$(acpi | awk '{print $4}')
  REMAINING=$(acpi | awk '{print $5}')

  TLEFT=$(tr ':' 'h' <<< ${REMAINING::-3})
  echo $STATUS $LEVEL $TLEFT left
  
  PLEVEL=${LEVEL::-2}
  
  if [[ $PLEVEL -eq 10 ]]; then
    dunstify -u "critical" 'Bateria fraca -- 10%'
  elif [[ $PLEVEL -eq 5 ]]; then
    notify-send "Desligando em 1 minuto"
    sleep 60


    STATUS=$(acpi | awk '{print $3}')

  if [[ $STATUS == 'Discharging,' ]]; then
    poweroff
  fi  
fi

elif [[ $STATUS == 'Charging,' ]]; then
  LEVEL=$(acpi | awk '{print $4}')
  REMAINING=$(acpi | awk '{print $5}')
  FIS=${REMAINING::-7}
  
  if [[ $FIS != '0' ]]; then
    REMAINING="Calculating......"
  else
    TLEFT=$(tr ':' 'h' <<< ${REMAINING::-3})
    echo $STATUS $LEVEL $TLEFT to full
  fi
else
  echo
fi

