#!/bin/bash

name=$(ls $1 | rofi -font "Fira Code 13" -theme Arc-Dark -dmenu -p "Select book: " -i)


if [[ -d "$1/$name" ]]; then
  book "$1/$name"
  exit
fi


if [[ -f "$1/$name" ]]; then
  if [[ $name == *.epub ]] then
    fbreader "$1/$name"
  else
    zathura  "$1/$name"
  fi
fi
