#!/bin/bash

function send_notification() {
	brightness=$(printf "%.2f\n" $(brillo -G))
	dunstify -a "changebrightness" -u low -r 9991 -h int:value:"$brightness" "Brightness: $brightness%" -t 2000
}


xrand_brighness=$(xrandr --verbose | grep Brightness | awk '{print $2}')


if [[ $(brillo) == '0.00' ]] && [[ $1 == 'down' ]]; then
	ajust="xrandr"
elif [[ $(brillo) == '0.00' ]] && [[ $1 == 'up' ]]; then
	if (( $(echo "$xrand_brighness < 1" |bc -l) )); then
		ajust="xrandr"
	else
		ajust="brillo"
	fi
else
	ajust="brillo"
fi


if [[ $ajust == 'brillo' ]]; then
	case $1 in
	up)
		pkexec brillo -A 3 -q
		send_notification  
 		;;
	down)
		pkexec brillo -U 3 -q
		send_notification  
		;;
	esac
elif [[ $ajust == 'xrandr' ]]; then

	xrandr_up=$(awk '{print $1+0.05}' <<<"${xrand_brighness}")
	xrandr_down=$(awk '{print $1-0.05}' <<<"${xrand_brighness}")

	case $1 in
		up)
			xrandr --output eDP-1 --brightness $xrandr_up
			xrandr_bar=$(awk '{print $1*100}' <<<"${xrandr_up}")
			notify-send -u low -r 9991 -h int:value:$xrandr_bar  "xrandr brightness $xrandr_bar"
			# send_notification $1
			;;
		down)
			xrandr --output eDP-1 --brightness $xrandr_down
			xrandr_bar=$(awk '{print $1*100}' <<<"${xrandr_down}")
			notify-send -u low -r 9991 -h int:value:$xrandr_bar "xrandr brightness $xrandr_bar%"
			# send_notification $1
			;;
		esac
fi
