#! /bin/bash

echo 80 > /sys/class/power_supply/CMB0/charge_control_end_threshold
echo 0 > /sys/devices/platform/lg-laptop/leds/tpad_led/brightness

echo 0 > /sys/devices/platform/lg-laptop/fan_mode
echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
