#!/bin/bash

function send_notification() {
	volume=$(pactl list sink-inputs | grep -B 16 mocp | grep Volume | awk '{print $5}')
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume MOCP: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	mocp -v +5
	send_notification $1
	;;
down)
	mocp -v -5
	send_notification $1
	;;
esac
